[package]
name = "simple-spline"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
readme = "README.md"
keywords = ["splines", "curves", "graphics", "inversion", "cubic"]
categories = ["mathematics", "graphics", "multimedia", "no-std"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Simple cubic spline evaluation."
documentation = "https://docs.rs/simple-spline/"
repository = "https://github.com/virtualritz/simple-spline/"

[dependencies]
num-traits = "0.2.14"
roots = "0.0.6"
lerp = "0.3.0"
